version: 2

sources:
  - name: omop_data
    database: aml_report
    schema: aml_schema

    tables:
      - name: person
        description: "OMOP Person table containing demographic data."
      - name: death
        description: "OMOP Death table containing death information."
      - name: observation_period
        description: "OMOP Observation Period table containing periods of observation."
      - name: vocabulary
        description: "OMOP Vocabulary table containing concept definitions."
      - name: cdm_source
        description: "OMOP CDM Source table containing metadata about the source data."
    # Uncomment if visit_occurrence and condition_occurrence are needed
    # - name: visit_occurrence
    #   description: "OMOP Visit Occurrence table containing visit details."
    # - name: condition_occurrence
    #   description: "OMOP Condition Occurrence table containing medical conditions."

models:
  - name: person
    description: "OMOP Person table containing demographic data."
    columns:
      - name: person_id
        description: "Unique identifier for each person."
        tests:
          - not_null
          - unique
      - name: year_of_birth
        description: "Year of birth of the person."
        tests:
          - not_null
  
  - name: death
    description: "OMOP Death table containing death information."
    columns:
      - name: person_id
        description: "Unique identifier for each person."
        tests:
          - not_null
      - name: death_date
        description: "Date of death."
        tests:
          - not_null

  - name: observation_period
    description: "OMOP Observation Period table containing periods of observation."
    columns:
      - name: person_id
        description: "Unique identifier for each person."
        tests:
          - not_null
      - name: observation_period_start_date
        description: "Start date of the observation period."
        tests:
          - not_null
      - name: observation_period_end_date
        description: "End date of the observation period."
        tests:
          - not_null
      - name: observation_period_id
        description: "Unique identifier for the observation period."
        tests:
          - not_null
          - unique

  - name: cdm_source
    description: "OMOP CDM Source table containing metadata about the source data."
    columns:
      - name: cdm_source_name
        description: "Name of the source data."
        tests:
          - not_null
      - name: cdm_source_abbreviation
        description: "Abbreviation for the source data."
        tests:
          - not_null

  # - name: visit_occurrence
  #   description: "OMOP Visit Occurrence table containing visit details."
  #   columns:
  #     - name: person_id
  #       description: "Unique identifier for each person."
  #       tests:
  #         - not_null
  #     - name: visit_concept_id
  #       description: "Concept ID for the type of visit."
  #       tests:
  #         - not_null
  #     - name: visit_start_date
  #       description: "Start date of the visit."
  #       tests:
  #         - not_null
  #     - name: visit_end_date
  #       description: "End date of the visit."
  #       tests:
  #         - not_null
      
  # - name: condition_occurrence
  #   description: "OMOP Condition Occurrence table containing medical conditions."
  #   columns:
  #     - name: person_id
  #       description: "Unique identifier for each person."
  #       tests:
  #         - not_null
  #     - name: condition_concept_id
  #       description: "Concept ID for the condition."
  #       tests:
  #         - not_null
  #     - name: condition_start_date
  #       description: "Start date of the condition occurrence."
  #       tests:
  #         - not_null
  #     - name: condition_end_date
  #       description: "End date of the condition occurrence."
  #       tests:
  #         - not_null